### ISSUE TITLE
else if does not count the if ?

### ISSUE THREAD

**Issue by uael** [anvaka/common-words#2]
It seems that when "else if" is matched, the "if" isn't counted

**Comment by anvaka** [comment]
Thank you for reporting.

While top words were correct, the usage counters were skewed. I was showing number of occurrences for a top word only inside top lines. 

This should be fixed by https://github.com/anvaka/common-words/commit/7966bc66970ac198965983a21cf2c96db0e8c6ba

Top words now show absolute word usage count, while context lines show how many such line appeared.
